ALTER TABLE `Subject` CHANGE `Lab` `Lab` INT(11) NULL DEFAULT NULL, CHANGE `Tutorial` `Tutorial` INT(11) NULL DEFAULT NULL,
CHANGE `Elective` `Elective` INT(11) NULL DEFAULT NULL, CHANGE `SelfStudy` `SelfStudy` INT(11) NULL DEFAULT NULL;
